### PR TITLE
Fixed threading issues causing freezes when server is unavailable

### PR DESCRIPTION
**Pull request by cezary-butler**
Fixed threading issues causing freezes when server is unavailable,
Refactoring (as side effect of above)
Dropped commons-io dependency.

### CODE REVIEW

**Comment by dboissier** [comment]
Hi,

I currently make your pull request work with java 1.6 (because Idea is always built with it). It should be ok on the next monday.

I will keep your informed  when it is ready.

Have a nice WE and thanks for your great job on this plugin.

**Comment by cezary-butler** [comment]
Are sure that idea is still built with Java 6?
I'm was pretty sure that last versions (since 14.1) are being built with Java 8 (and certainly run with Java 8 - except mac which runs on Java 7).

**Comment by dboissier** [comment]
Hi,

I tried to launch the plugin within the plugin-sand box and I got the folling error:
```
/home/dboissier/applications/jdk1.7.0_51/bin/java -Xmx512m -Xms256m -XX:MaxPermSize=250m -Xbootclasspath/a:/home/dboissier/applications/idea-IC-135.1306/lib/boot.jar -Didea.config.path=/home/dboissier/.IntelliJIdea14/system/plugins-sandbox/config -Didea.system.path=/home/dboissier/.IntelliJIdea14/system/plugins-sandbox/system -Didea.plugins.path=/home/dboissier/.IntelliJIdea14/system/plugins-sandbox/plugins -Dsun.awt.disablegrab=true -Didea.platform.prefix=Idea -Didea.launcher.port=7532 -Didea.launcher.bin.path=/home/dboissier/applications/idea-IU-141.2735.5/bin -Dfile.encoding=UTF-8 -classpath /home/dboissier/applications/jdk1.7.0_51/lib/tools.jar:/home/dboissier/applications/idea-IC-135.1306/lib/idea_rt.jar:/home/dboissier/applications/idea-IC-135.1306/lib/idea.jar:/home/dboissier/applications/idea-IC-135.1306/lib/bootstrap.jar:/home/dboissier/applications/idea-IC-135.1306/lib/extensions.jar:/home/dboissier/applications/idea-IC-135.1306/lib/util.jar:/home/dboissier/applications/idea-IC-135.1306/lib/openapi.jar:/home/dboissier/applications/idea-IC-135.1306/lib/trove4j.jar:/home/dboissier/applications/idea-IC-135.1306/lib/jdom.jar:/home/dboissier/applications/idea-IC-135.1306/lib/log4j.jar:/home/dboissier/applications/idea-IU-141.2735.5/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain com.intellij.idea.Main
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.awt.Component.<clinit>(Component.java:595)
	at com.intellij.idea.Main.showMessage(Main.java:209)
	at com.intellij.idea.Main.showMessage(Main.java:196)
	at com.intellij.idea.Main.main(Main.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Process finished with exit code 1
```

Do you have any idea? Perhaps, I made a mistake in the Intellij SDK configuration.

Regards.

**Comment by dboissier** [comment]
Hi,

Unless it is outdated, the [README](https://github.com/JetBrains/intellij-community/blob/master/README.md) of intellij community seems to make to Intellij SDK point to jdk 1.6.

What do you think?

**Comment by cezary-butler** [comment]
I'd say this README is relevant to idea development (with bundled plugins). Not to plugins distributed separately. Of course remembering about limitations mentioned before.

About error, I never had such problem but I also always ran plugin directly from Idea, not using maven or java directly.
For me looks like something missing on classpath.

**Comment by dboissier** [comment]
Ok

I will follow your recommendations and will build the plugin with java 1.7. It should be released by the end of tomorrow.

Thanks for your advices.

**Comment by dboissier** [comment]
Hi,
please review the CHANGELOG and tell me if it reflects the work you've done (if not, please update it)

After that, I will release the plugin.

I usually make an announcement on twitter. If you have an twitter id, I could mention you as the hero of this release :)

**Comment by cezary-butler** [comment]
I don't have twitter account, but It'd be great if you could also merge #98 which allows plugin to run in Idea 15. It's one simple change in JenkinsWidget

**Comment by dboissier** [comment]
got that

**Comment by dboissier** [comment]
Hi,

The plugin is deployed on jetbrains repository

**Pull request merged**
